"""Add season start & end dates

Revision ID: 51a51f77253c
Revises: 7696ed1c2bd3
Create Date: 2018-03-04 21:14:33.129326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a51f77253c'
down_revision = '7696ed1c2bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('competitions', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'start_date')
    op.drop_column('competitions', 'end_date')
    # ### end Alembic commands ###
