"""Add short_name to teams table

Revision ID: 4301546e6ec3
Revises: f24d01ebb713
Create Date: 2018-03-03 10:41:39.397090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4301546e6ec3'
down_revision = 'f24d01ebb713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('short_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'short_name')
    # ### end Alembic commands ###
